server:
    port: 8010

spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test
        username: jayden
        password: P@ssw0rd
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console.enabled: true
